GET http://127.0.0.1:8080/document/secret/PRT45

###
POST http://127.0.0.1:8080/document/secret/PRT45
Content-Type: application/json 

{
  "protocolNumber": "AREA-51-X", 
  "title": "Progetto Alieno Top Secret",
  "confidentialityReason": "Livello Massimo Sicurezza Nazionale",
  "content": "Gli alieni sono atterrati in Nevada.",
  "author": "Agente Mulder",
  "hashSignature": "TrustNoOne"
}

###
POST http://127.0.0.1:8080/document/secret/PRB46
Content-Type: application/json 

{
  "protocolNumber": "OMEGA-17",
  "title": "Operazione Fenice",
  "confidentialityReason": "Segreto di Stato",
  "content": "Dettagli sull'operazione di recupero dati sensibili.",
  "author": "Agente Smith",
  "hashSignature": "RedPillBluePill"
}

###
GET http://127.0.0.1:8080/document/secret/AREA-51-X/PRT45

###
###Codice Errato
GET http://127.0.0.1:8080/document/secret/AREA-51-X/PIPPO